# Generated by Django 5.2.8 on 2025-11-11 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('temp_c', models.FloatField()),
                ('limit_c', models.FloatField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_limit_c', models.FloatField(default=30.0)),
                ('check_every_min', models.PositiveIntegerField(default=30)),
                ('lat', models.FloatField(default=-23.55)),
                ('lon', models.FloatField(default=-46.63)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('temp_c', models.FloatField()),
                ('source', models.CharField(default='open-meteo', max_length=50)),
            ],
        ),
    ]
